baseURL = "https://haiku-inc.org/"
languageCode = "en-us"
title = "Haiku, Inc."
theme = "hugo-smorg"
copyright = "&copy; 2003-2026 Haiku, Inc. All Rights reserved."

[params]
fullname = " "
logotype = "<img src='/images/haiku_inc_logo.png' alt='Haiku Inc. Logo'> <span class='has-text-weight-bold'>Haiku, <span class='has-text-danger'>Inc.</span></span>"
footer = " "
subfooter = " "

[markup.goldmark.renderer]
	unsafe = true

[[menu.sectionmenu]]
	name = "About"
	url = "about/"
	weight = 10
[[menu.sectionmenu]]
	name = "FAQ"
	url = "about/faq"
	weight = 20
[[menu.sectionmenu]]
	name = "Trademarks"
	url = "trademarks/"
	weight = 30
	identifier = "trademarks"
[[menu.sectionmenu]]
	name = "Usage Requirements"
	url = "trademarks/usage_requirements"
	weight = 10
	parent = "trademarks"
[[menu.sectionmenu]]
	name = "Allowed Usage"
	url = "trademarks/allowed_usage"
	weight = 20
	parent = "trademarks"
[[menu.sectionmenu]]
	name = "Logo Design"
	url = "trademarks/logo_design"
	weight = 30
	parent = "trademarks"
[[menu.sectionmenu]]
	name = "Haiku's icons"
	url = "trademarks/haiku_icons"
	weight = 40
	parent = "trademarks"
[[menu.sectionmenu]]
	name = "Documents"
	url = "documents/"
	identifier = "documents"
	weight = 40
[[menu.sectionmenu]]
	name = "Source code licenses"
	url = "documents/licenses"
	parent = "documents"
	weight = 10
[[menu.sectionmenu]]
	name = "Donation tracking"
	url = "documents/donations"
	parent = "documents"
	weight = 20
[[menu.sectionmenu]]
	name = "Requesting funds"
	url = "documents/requesting_funds"
	parent = "documents"
	weight = 30
[[menu.sectionmenu]]
	name = "Donate"
	url = "donate/"
	weight = 50
	identifier = "donate"
[[menu.sectionmenu]]
	name = "Funded development"
	url = "donate/funded_development"
	parent = "donate"
	weight = 10
[[menu.sectionmenu]]
	name = "Infrastructure"
	url = "donate/infrastructure"
	parent = "donate"
	weight = 20
[[menu.sectionmenu]]
	name = "Hardware"
	url = "donate/hardware"
	parent = "donate"
	weight = 30
[[menu.sectionmenu]]
	name = "Public Sponsors"
	url = "donate/public_sponsors"
	parent = "donate"
	weight = 40
[[menu.sectionmenu]]
	name = "Privacy Policy"
	url = "donate/privacy_policy"
	parent = "donate"
	weight = 50
[[menu.sectionmenu]]
	name = "Contact"
	url = "contact/"
	weight = 60
